CREATE SCHEMA PIZZARIA;

SET search_path = PIZZARIA;

CREATE TABLE PEDIDOS (
    ID_PEDIDO int PRIMARY KEY,
    PRODUTOS VARCHAR(100),
    DATA_HORA VARCHAR(100),
    CPF_ENTREGADOR VARCHAR(11)

    FOREIGN KEY (CPF_ENTREGADOR)
    REFERENCES ENTREGADORES(CPF_ENTREGADOR)
);

CREATE TABLE ENTREGADORES (
    CPF_ENTREGADOR VARCHAR(11) PRIMARY KEY,
    NOME_ENTREGADOR VARCHAR(100)
);

CREATE TABLE BOLETIM_OCORRENCIA (
    ID_BOLETIM int PRIMARY KEY,
    CPF_PESSOA_BOLETIM VARCHAR(11),
    DESCRICAO_BOLETIM VARCHAR(100),

    FOREIGN KEY (CPF_PESSOA_BOLETIM)
    REFERENCES SISTEMA_CRIMINAL(CPF_PESSOA_BOLETIM)

);

CREATE TABLE SISTEMA_RADAR (
    ID_CAMERA int PRIMARY KEY,
    LOCAL_RADAR VARCHAR(100),
    DATA_HORA_RADAR VARCHAR(100),
    PLACA_RADAR VARCHAR(100),
    DESCRICAO_RADAR VARCHAR(100)
);

CREATE TABLE LOJA_CAPACETE (
    ID_PRODUTO int PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100),
    CPF_COMPRADOR VARCHAR(11),
    VALOR_PRODUTO float,

    FOREIGN KEY (CPF_COMPRADOR)
    REFERENCES COMPRADORES(CPF_COMPRADOR)
);

CREATE TABLE COMPRADORES (
    CPF_COMPRADOR VARCHAR(11) PRIMARY KEY,
    NOME_COMPRADOR VARCHAR(100)
);

CREATE TABLE SISTEMA_CRIMINAL (
    CPF_PESSOA VARCHAR(11) PRIMARY KEY,
    NOME_PESSOA VARCHAR(100),
    DATA_NASCIMENTO_PESSOA VARCHAR(100),
    ENDERECO_PESSOA VARCHAR(100),
    DESCRICAO VARCHAR(100)
);